### ISSUE TITLE
Modal example is not a jsPanel

### ISSUE THREAD

**Issue by Flyer53** [priteshjha4u/react-jspanel4#1]
First of all thanks for this repo. I'm sure it will be of help ...
Just one thing: the modal example is not a jsPanel. Since jsPanel offers the use as modal a well I would appreciate it a lot if you could consider changing your example to use a jsPanel modal.
Thanks again and best regards,
Stefan

**Comment by priteshjha4u** [comment]
Hi @Flyer53 
I am so glad you have noticed this little piece of work.
Yes, you are right, the modal example is just a plain bootstrap modal.
I would certainly fix that asap.

Thank you for your great work.

**Comment by Flyer53** [comment]
@priteshjha4u 
Thanks for the praise 😄 My pleasure
In case you didn't notice yet ... I spent some time lately working on jsPanel v4.7.0 and since the changelog is relatively long I published a v4.7.0-beta on https://beta.jspanel.de/index.html you might want to check out.
I also linked to your "little piece of work" on the getting started page https://beta.jspanel.de/getstarted.html#angular and the FAQs.

**Comment by priteshjha4u** [comment]
Hey @Flyer53 ,
Thank you for putting my work reference on your web page. :smiley:
FYI, I have fixed this issue and also refactored overall code to look more elegant and maintainable.
Checkout latest build [here](https://priteshjha4u.github.io/react-jspanel4/)

Happy coding. :smiley: :+1:

**Comment by Flyer53** [comment]
👍 Great! 🥇 
Thank you very much.
I appreciate that a lot !!

**Comment by priteshjha4u** [comment]
This can be closed.
