### ISSUE TITLE
Pass Component

### ISSUE THREAD

**Issue by raulcesar54** [priteshjha4u/react-jspanel4#10]
When I pass a component to the content, it returns [Object object] how could I solve it?

![image](https://user-images.githubusercontent.com/50491912/93669616-70d5fd80-fa63-11ea-8ff3-af70688b1d76.png)
![image](https://user-images.githubusercontent.com/50491912/93669624-7f241980-fa63-11ea-921e-e0d57de6c556.png)

**Comment by priteshjha4u** [comment]
Hi @raulcesar54 

You can't pass a react component like that to jsPanel. Please see the example `app.js` to understand how this should be done.
